dist: xenial
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - '9'
before_script:
  - npm prune
script:
  - xvfb-run --server-args="-screen 0 1024x768x24" make test
after_success:
  - npm run report-coverage
deploy:
  - provider: script
    script: npx semantic-release -r
      https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    skip_cleanup: true
    keep_history: true
    on:
      branch: master
branches:
  only:
  - master
services:
  - xvfb
install:
  - npm install
