os: linux
dist: bionic
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - "16.2.0"
jobs:
  include:
    - stage: test
      script: npm run test
      after_success:
        - npm run report-coverage
    - stage: npm release
      if: branch = master
      script:
        - echo "Deploying to npm ..."
      deploy:
        provider: script
        script: npx semantic-release
        on:
          branch: master
services:
  - xvfb