import iconCitation from '@src/icons/address-card-solid.svg';
import titleIcon from '@src/icons/book-solid.svg';
import rsIcon from '@src/icons/box-open-solid.svg';
import validateIcon from '@src/icons/clipboard-check-solid.svg';
import codeIcon from '@src/icons/code-solid.svg';
import editIcon from '@src/icons/edit-solid.svg';
import EventIcon from '@src/icons/event.svg';
import ExclamationIcon from '@src/icons/exclamation-mark.svg';
import markupFileIcon from '@src/icons/file-code-solid.svg';
import loadIcon from '@src/icons/folder-open-solid.svg';
import KeyIcon from '@src/icons/key.svg';
import LabelIcon from '@src/icons/label.svg';
import LinkIcon from '@src/icons/link.svg';
import iconPerson from '@src/icons/person.svg';
import PlaceIcon from '@src/icons/place.svg';
import relationIcon from '@src/icons/project-diagram-solid.svg';
import saveIcon from '@src/icons/save-solid.svg';
import signOutIcon from '@src/icons/sign-out-alt-solid.svg';
import NoteIcon from '@src/icons/sticky-note-2.svg';
import tagEditIcon from '@src/icons/tag-edit-solid.svg';
import tagRemoveIcon from '@src/icons/tag-remove-solid.svg';
import TranslationIcon from '@src/icons/translate.svg';
import iconOrg from '@src/icons/users-solid.svg';
import { Editor } from 'tinymce/tinymce';

export const addIconPack = (editor: Editor) => {
  editor.ui.registry.addIcon('tags', LabelIcon);
  editor.ui.registry.addIcon('person', iconPerson);
  editor.ui.registry.addIcon('place', PlaceIcon);
  editor.ui.registry.addIcon('title', titleIcon);
  editor.ui.registry.addIcon('date', EventIcon);
  editor.ui.registry.addIcon('organization', iconOrg);
  editor.ui.registry.addIcon('citation', iconCitation);
  editor.ui.registry.addIcon('note', NoteIcon);
  editor.ui.registry.addIcon('correction', ExclamationIcon);
  editor.ui.registry.addIcon('keyword', KeyIcon);
  editor.ui.registry.addIcon('link', LinkIcon);
  editor.ui.registry.addIcon('rs', rsIcon);
  editor.ui.registry.addIcon('translation', TranslationIcon);
  editor.ui.registry.addIcon('relation', relationIcon);
  editor.ui.registry.addIcon('tag-edit', tagEditIcon);
  editor.ui.registry.addIcon('tag-remove', tagRemoveIcon);
  editor.ui.registry.addIcon('code', codeIcon);
  editor.ui.registry.addIcon('markup-file', markupFileIcon);
  editor.ui.registry.addIcon('edit', editIcon);
  editor.ui.registry.addIcon('validate', validateIcon);
  editor.ui.registry.addIcon('save', saveIcon);
  editor.ui.registry.addIcon('load', loadIcon);
  editor.ui.registry.addIcon('sign-out', signOutIcon);
};
